version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8000:8000'
    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./.docker_env:/app/animal_site/.env
  db:
    restart: always
    image: postgres
    container_name: animal_db
    environment:
      - POSTGRES_USER=animal_user
      - POSTGRES_PASSWORD=q123456
      - POSTGRES_DB=animal
      - POSTGRES_PORT=5432
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: