version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8001:8001'
    command: >
      bash -c " python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8001"
  db:
    restart: always
    image: postgres
    container_name: animal_db
    env_file:
      - .docker_env
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: