# Generated by Django 4.1.1 on 2022-10-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_article', models.TextField(help_text='Введите информацию, которая будет отображаться в шапке на главной. 250 символов максимум.', max_length=250, verbose_name='Информация о нас')),
                ('about_footer', models.TextField(help_text='Введите информацию, которая будет отображаться внизу страниц, в футере. 50 символов максимум.', max_length=50, verbose_name='Информация о нас')),
                ('about_body', models.TextField(help_text='Введите информацию, которая будет отображаться на странице о компании. 500 символов максимум.', max_length=500, verbose_name='Информация о нас')),
            ],
            options={
                'verbose_name': 'Информация',
                'verbose_name_plural': 'Информации',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_pdf', models.FileField(help_text='Прикрепите прайс лист', upload_to='price_doc/', verbose_name='Прайс лист')),
            ],
            options={
                'verbose_name': 'Прайс лист',
                'verbose_name_plural': 'Прайс листы',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='Введите вопрос, который будет отображаться в FAQ. 50 символов максимум.', max_length=50, verbose_name='Вопрос в FAQ')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(help_text='Вставьте ссылку на телеграмм', max_length=50, verbose_name='Ссылка на телеграмм')),
                ('vk', models.CharField(help_text='Вставьте ссылку на вконтакте', max_length=50, verbose_name='Ссылка на вконтакте')),
                ('whatsapp', models.CharField(help_text='Вставьте ссылку на whatsapp', max_length=50, verbose_name='Ссылка на whatsapp')),
            ],
            options={
                'verbose_name': 'Соцсети',
                'verbose_name_plural': 'Соцсети',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(help_text='Введите ответ на вопрос, который будет отображаться в FAQ. 500 символов максимум.', max_length=500, verbose_name='Ответ на вопрос в FAQ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='info.questions')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
