# Generated by Django 4.1.1 on 2022-10-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': 'Информация', 'verbose_name_plural': 'Информации'},
        ),
        migrations.AlterModelOptions(
            name='pricelist',
            options={'verbose_name': 'Прайс лист', 'verbose_name_plural': 'Прайс листы'},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Соцсети', 'verbose_name_plural': 'Соцсети'},
        ),
    ]
