# Generated by Django 4.1.1 on 2022-10-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория животного', 'verbose_name_plural': 'Категории животного'},
        ),
    ]
