# Generated by Django 4.1.1 on 2022-09-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animals',
            options={'verbose_name': 'Питомец клуба', 'verbose_name_plural': 'Питомцы клуба'},
        ),
    ]
