# Generated by Django 4.1.1 on 2022-10-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_alter_animals_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
