# Generated by Django 4.1.1 on 2022-10-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='review',
            field=models.TextField(blank=True, help_text='Введите отзыва', null=True, verbose_name='Отзыв'),
        ),
    ]
