# Generated by Django 4.1.1 on 2022-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(choices=[('Breeder', 'Заводчик'), ('Client', 'Клиент')], default='Breeder', max_length=35, verbose_name='Тип клиента'),
        ),
    ]
